// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Presensi struct {
	ID     int64     `json:"id"`
	UserID int64     `json:"user_id"`
	Foto   string    `json:"foto"`
	Time   time.Time `json:"time"`
	Lat    string    `json:"lat"`
	Lng    string    `json:"lng"`
	Alamat string    `json:"alamat"`
}

type Session struct {
	ID     int64          `json:"id"`
	UserID int64          `json:"user_id"`
	Token  string         `json:"token"`
	Time   time.Time      `json:"time"`
	Device string         `json:"device"`
	Status sql.NullString `json:"status"`
}

type User struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Pasword  string `json:"pasword"`
	UserType string `json:"user_type"`
}
