// Code generated by sqlc. DO NOT EDIT.
// source: session.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO "Sessions" (
  user_id, token, device
) VALUES (
  $1, $2, $3
)
RETURNING id, user_id, token, time, device, status
`

type CreateSessionParams struct {
	UserID int64  `json:"user_id"`
	Token  string `json:"token"`
	Device string `json:"device"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.UserID, arg.Token, arg.Device)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Time,
		&i.Device,
		&i.Status,
	)
	return i, err
}
